#include <ctype.h>
#include "vasm.h"

#include "vasm_rv32m.h"

#define SYM_INSTR_EXT "32m"

symbol_t sym_instr_rv32m[] =
{
    SYM_INSTR_X(mul,FORMAT_R_CODE(OPCODE_ARITH,FUNCT_MUL,FUNCT7_MULDIV),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(mulh,FORMAT_R_CODE(OPCODE_ARITH,FUNCT_MULH,FUNCT7_MULDIV),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(mulhsu,FORMAT_R_CODE(OPCODE_ARITH, FUNCT_MULHSU,FUNCT7_MULDIV),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(mulhu,FORMAT_R_CODE(OPCODE_ARITH,FUNCT_MULHU,FUNCT7_MULDIV),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(div, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_DIV,FUNCT7_MULDIV),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(divu, FORMAT_R_CODE(OPCODE_ARITH, FUNCT_DIVU,FUNCT7_MULDIV),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1,ASM_REG_RS2)),

    SYM_INSTR_X(rem, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_REM,FUNCT7_MULDIV),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(remu, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_REMU,FUNCT7_MULDIV),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),
};

int vasm_rv32m_table_load(vasm_ctx_t* ctx)
{
    DEBUGF(ctx, "rv32m table load\n");
    symbol_table_install_array(&ctx->symtab, &sym_instr_rv32m[0],
			       sizeof_array(sym_instr_rv32m));
    return 0;
}
