#include <ctype.h>
#include "vasm.h"

#include "vasm_rv32i.h"

#define SYMREG_XI(i, nm) \
    [(i)] = { .next = 0, .flags = SYMBOL_FLAG_REG, .index = (i), .name = (nm)  }

symbol_t sym_reg_xi[] =
{
    SYMREG_XI(0, "x0"),
    SYMREG_XI(1, "x1"),
    SYMREG_XI(2, "x2"),
    SYMREG_XI(3, "x3"),
    SYMREG_XI(4, "x4"),
    SYMREG_XI(5, "x5"),
    SYMREG_XI(6, "x6"),
    SYMREG_XI(7, "x7"),
    SYMREG_XI(8, "x8"),
    SYMREG_XI(9, "x9"),
    SYMREG_XI(10, "x10"),
    SYMREG_XI(11, "x11"),
    SYMREG_XI(12, "x12"),
    SYMREG_XI(13, "x13"),
    SYMREG_XI(14, "x14"),
    SYMREG_XI(15, "x15"),
    SYMREG_XI(16, "x16"),
    SYMREG_XI(17, "x17"),
    SYMREG_XI(18, "x18"),
    SYMREG_XI(19, "x19"),
    SYMREG_XI(20, "x20"),
    SYMREG_XI(21, "x21"),
    SYMREG_XI(22, "x22"),
    SYMREG_XI(23, "x23"),
    SYMREG_XI(24, "x24"),
    SYMREG_XI(25, "x25"),
    SYMREG_XI(26, "x26"),
    SYMREG_XI(27, "x27"),
    SYMREG_XI(28, "x28"),
    SYMREG_XI(29, "x29"),
    SYMREG_XI(30, "x30"),
    SYMREG_XI(31, "x31"),
};

char* register_xi_name(int r)
{
    return sym_reg_xi[r].name;
}

#define SYMREG_ABI(i, nm) \
    [(i)] = { .next = 0, .flags = SYMBOL_FLAG_REG, .index = (i), .name = (nm)  }

#define SYMREG_ABI_IX(i,ix,nm)						\
    [(i)] = { .next = 0, .flags = SYMBOL_FLAG_REG, .index = (ix), .name = (nm)  }

symbol_t sym_reg_abi[] = 
{
    SYMREG_ABI(0, "zero"),
    SYMREG_ABI(1, "ra"),
    SYMREG_ABI(2, "fp"),
    SYMREG_ABI(3, "s1"),
    SYMREG_ABI(4, "s2"),
    SYMREG_ABI(5, "s3"),
    SYMREG_ABI(6, "s4"),
    SYMREG_ABI(7, "s5"),
    SYMREG_ABI(8, "s6"),
    SYMREG_ABI(9, "s7"),
    SYMREG_ABI(10, "s8"),
    SYMREG_ABI(11, "s9"),
    SYMREG_ABI(12, "s10"),
    SYMREG_ABI(13, "s11"),
    SYMREG_ABI(14, "sp"),
    SYMREG_ABI(15, "tp"),
    SYMREG_ABI(16, "v0"),
    SYMREG_ABI(17, "v1"),
    SYMREG_ABI(18, "a0"),
    SYMREG_ABI(19, "a1"),
    SYMREG_ABI(20, "a2"),
    SYMREG_ABI(21, "a3"),
    SYMREG_ABI(22, "a4"),
    SYMREG_ABI(23, "a5"),
    SYMREG_ABI(24, "a6"),
    SYMREG_ABI(25, "a7"),
    SYMREG_ABI(26, "t0"),
    SYMREG_ABI(27, "t1"),
    SYMREG_ABI(28, "t2"),
    SYMREG_ABI(29, "t3"),
    SYMREG_ABI(30, "t4"),
    SYMREG_ABI(31, "gp"),
    SYMREG_ABI_IX(32, 2, "s0"),
};

char* register_abi_name(int r)
{
    return sym_reg_abi[r].name;
}

symbol_t sym_instr_rv32i[] =
{
    SYM_INSTR_X(add, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_ADD,0),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(sub, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_SUB,0x20),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1,ASM_REG_RS2)),

    SYM_INSTR_X(sll, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_SLL,0),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(srl, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_SRL,0),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(sra, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_SRA,0x20),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(and, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_AND,0),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(or, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_OR,0),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(xor, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_XOR,0),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(slt, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_SLT,0),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(sltu, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_SLTU,0),
		FORMAT_R, FORMAT_R_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_REG_RS2)),

    SYM_INSTR_X(addi, FORMAT_I_CODE(OPCODE_IMM, FUNCT_ADDI),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_IMM_12)),

    SYM_INSTR_X(slli, FORMAT_I_CODE(OPCODE_IMM, FUNCT_SLLI),
		FORMAT_I, FORMAT_I_MASK|(0xfc000000),
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_SHAMT_5)),

    SYM_INSTR_X(srli, FORMAT_I_CODE(OPCODE_IMM, FUNCT_SRLI),
		FORMAT_I, FORMAT_I_MASK|(0xfc000000),
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_SHAMT_5)),

    SYM_INSTR_X(srai, FORMAT_I_CODE(OPCODE_IMM,FUNCT_SRAI)|(0x40000000),
		FORMAT_I, FORMAT_I_MASK|(0xfc000000),
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_SHAMT_5)),

    SYM_INSTR_X(andi, FORMAT_I_CODE(OPCODE_IMM, FUNCT_ANDI),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_IMM_12)),

    SYM_INSTR_X(ori, FORMAT_I_CODE(OPCODE_IMM, FUNCT_ORI),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_IMM_12)),

    SYM_INSTR_X(xori, FORMAT_I_CODE(OPCODE_IMM, FUNCT_XORI),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_IMM_12)),

    SYM_INSTR_X(slti, FORMAT_I_CODE(OPCODE_IMM, FUNCT_SLTI),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_IMM_12)),

    SYM_INSTR_X(sltiu, FORMAT_I_CODE(OPCODE_IMM, FUNCT_SLTIU),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ3(ASM_REG_RD, ASM_REG_RS1, ASM_IMM_12)),

    SYM_INSTR_X(lui, FORMAT_U_CODE(OPCODE_LUI),
		FORMAT_U, FORMAT_U_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_UIMM_20)),

    SYM_INSTR_X(auipc, FORMAT_U_CODE(OPCODE_AUIPC),
		FORMAT_U, FORMAT_U_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_UIMM_20)),

    SYM_INSTR_X(lb, FORMAT_I_CODE(OPCODE_LOAD, FUNCT_LB),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_IMM_12_RS1)),

    SYM_INSTR_X(lbu, FORMAT_I_CODE(OPCODE_LOAD, FUNCT_LBU),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_IMM_12_RS1)),

    SYM_INSTR_X(lh, FORMAT_I_CODE(OPCODE_LOAD, FUNCT_LH),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_IMM_12_RS1)),

    SYM_INSTR_X(lhu, FORMAT_I_CODE(OPCODE_LOAD, FUNCT_LHU),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_IMM_12_RS1)),

    SYM_INSTR_X(lw, FORMAT_I_CODE(OPCODE_LOAD, FUNCT_LW),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ2(ASM_REG_RS2, ASM_IMM_12_RS1)),

    SYM_INSTR_X(sb, FORMAT_SB_CODE(OPCODE_STORE,0),
		FUNCT_SB, FORMAT_SB_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_IMM_12_RS1)),

    SYM_INSTR_X(sh, FORMAT_S_CODE(OPCODE_STORE, FUNCT_SH),
		FORMAT_S, FORMAT_S_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_IMM_12_RS1)),

    SYM_INSTR_X(sw, FORMAT_S_CODE(OPCODE_STORE, FUNCT_SW),
		FORMAT_S, FORMAT_S_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_IMM_12_RS1)),

    SYM_INSTR_X(fence, FORMAT_I_CODE(OPCODE_FENCE, FUNCT_FENCE),
		FORMAT_I, FORMAT_I_MASK|(0xf00f8f80),
		ASM_SEQ2(ASM_IMM_IORW, ASM_IMM_IORW)),

    SYM_INSTR_NAME_X(fence_i, "fence.i",
		     FORMAT_I_CODE(OPCODE_FENCE, FUNCT_FENCE_I),
		     FORMAT_I, FORMAT_I_MASK|(0xffff8f80),
		     ASM_SEQ0()),

    SYM_INSTR_X(beq, FORMAT_SB_CODE(OPCODE_BRANCH,FUNCT_BEQ),
		FORMAT_SB, FORMAT_SB_MASK,
		ASM_SEQ3(ASM_REG_RS1, ASM_REG_RS2, ASM_REL_12)), 

    SYM_INSTR_X(bne, FORMAT_SB_CODE(OPCODE_BRANCH, FUNCT_BNE),
		FORMAT_SB, FORMAT_SB_MASK,
		ASM_SEQ3(ASM_REG_RS1, ASM_REG_RS2, ASM_REL_12)),

    SYM_INSTR_X(blt, FORMAT_SB_CODE(OPCODE_BRANCH, FUNCT_BLT),
		FORMAT_SB, FORMAT_SB_MASK,
		ASM_SEQ3(ASM_REG_RS1, ASM_REG_RS2, ASM_REL_12)),

    SYM_INSTR_X(bltu, FORMAT_SB_CODE(OPCODE_BRANCH, FUNCT_BLTU),
		FORMAT_SB, FORMAT_SB_MASK,
		ASM_SEQ3(ASM_REG_RS1, ASM_REG_RS2, ASM_REL_12)),

    SYM_INSTR_X(bge, FORMAT_SB_CODE(OPCODE_BRANCH, FUNCT_BGE),
		FORMAT_SB, FORMAT_SB_MASK,
		ASM_SEQ3(ASM_REG_RS1, ASM_REG_RS2, ASM_REL_12)),

    SYM_INSTR_X(bgeu, FORMAT_SB_CODE(OPCODE_BRANCH, FUNCT_BGEU),
		FORMAT_SB, FORMAT_SB_MASK,
		ASM_SEQ3(ASM_REG_RS1, ASM_REG_RS2, ASM_REL_12)),

    SYM_INSTR_X(jal, FORMAT_UJ_CODE(OPCODE_JAL),
		FORMAT_UJ, FORMAT_UJ_MASK,
		ASM_SEQ2(ASM_REG_RD, ASM_REL_20)),

    SYM_INSTR_X(jalr, FORMAT_I_CODE(OPCODE_JALR, 0),
		FORMAT_I, FORMAT_I_MASK,
		ASM_SEQ2(ASM_REG_RS2, ASM_IMM_12_RS1)),

    SYM_INSTR_X(scall, FORMAT_I_CODE(OPCODE_SYS, 0)|(0x00000000),
		FORMAT_I, FORMAT_I_MASK|(0xffff8f80),
		ASM_SEQ0()),
    SYM_INSTR_X(sbreak, FORMAT_I_CODE(OPCODE_SYS, 0)|(0x00100000),
		FORMAT_I, FORMAT_I_MASK|(0xffff8f80),
		ASM_SEQ0()),

    SYM_INSTR_X(rdcycle, FORMAT_I_CODE(OPCODE_SYS, 0)|(0xc0000000),
		FORMAT_I, FORMAT_I_MASK|(0xffff8000),
		ASM_SEQ1(ASM_REG_RD)),

    SYM_INSTR_X(rdcycleh,FORMAT_I_CODE(OPCODE_SYS, 0)|(0xc8000000),
		FORMAT_I, FORMAT_I_MASK|(0xffff8000),
		ASM_SEQ1(ASM_REG_RD)),

    SYM_INSTR_X(rdtime,FORMAT_I_CODE(OPCODE_SYS, 0)|(0xc0100000),
		FORMAT_I, FORMAT_I_MASK|(0xffff8000),
		ASM_SEQ1(ASM_REG_RD)),

    SYM_INSTR_X(rdtimeh,FORMAT_I_CODE(OPCODE_SYS, 0)|( 0xc8100000),
		FORMAT_I, FORMAT_I_MASK|(0xffff8000),
		ASM_SEQ1(ASM_REG_RD)),

    SYM_INSTR_X(rdinstret,FORMAT_I_CODE(OPCODE_SYS, 0)|(0xc0200000),
		FORMAT_I, FORMAT_I_MASK|(0xffff8000),
		ASM_SEQ1(ASM_REG_RD)),

    SYM_INSTR_X(rdinstreth,FORMAT_I_CODE(OPCODE_SYS, 0)|(0xc8200000),
		FORMAT_I, FORMAT_I_MASK|(0xffff8000),
		ASM_SEQ1(ASM_REG_RD)),
    
    // pseduo instructions

    // nop = addi x0,x0,0
    SYM_INSTR_X(nop, FORMAT_I_CODE(OPCODE_IMM, FUNCT_ADDI), 
		FORMAT_I, FORMAT_I_MASK|0xffffffff,
		ASM_SEQ0()),

    // mv = addi rd,rs1,0
    SYM_INSTR_X(mv, FORMAT_I_CODE(OPCODE_IMM,FUNCT_ADDI),
		FORMAT_I, FORMAT_I_MASK|0xfff00000,
		ASM_SEQ2(ASM_REG_RD, ASM_REG_RS1)),

    // seqz rd, rs1  = SLTIU rd, rs1, 1 - set equal zero
    SYM_INSTR_X(seqz, FORMAT_I_CODE(OPCODE_IMM, FUNCT_SLTIU)|0x00100000,
		FORMAT_I, FORMAT_I_MASK|0xfff00000,
		ASM_SEQ2(ASM_REG_RD, ASM_REG_RS1)),

    // snez rd, rs1  = SLTU rd, x0, rs2 - set not zero
    SYM_INSTR_X(snez, FORMAT_R_CODE(OPCODE_ARITH,FUNCT_SLTU,0),
		FORMAT_R, FORMAT_R_MASK|(0x000f8000),
		ASM_SEQ2(ASM_REG_RD, ASM_REG_RS2)),

    // not rd, rs1  = XORI rd, rs1, -1 - bitwise negation
    SYM_INSTR_X(not, FORMAT_I_CODE(OPCODE_IMM, FUNCT_XORI)|0xfff00000,
		FORMAT_I, FORMAT_I_MASK|0xfff00000,
		ASM_SEQ2(ASM_REG_RD, ASM_REG_RS1)),

    // j = jal x0,<imm>  - unconditional jump
    SYM_INSTR_X(j, FORMAT_UJ_CODE(OPCODE_JAL),
		FORMAT_UJ, FORMAT_UJ_MASK|0x00000f80,
		ASM_SEQ1(ASM_REL_20)),

    // li = addi <r>,x0,<imm>  - load 12bit immediate
    SYM_INSTR_X(li, FORMAT_I_CODE(OPCODE_IMM, FUNCT_ADDI),
		FORMAT_I, FORMAT_I_MASK|0x000e0000,
                ASM_SEQ2(ASM_REG_RD, ASM_IMM_12)),

    // inc = addi <r>,<r>,1
//   we can not match <r>, <r> in disasm yet so we wait
//    SYM_INSTR_X(inc, FORMAT_I_CODE(OPCODE_IMM, FUNCT_ADDI)|0x00100000,
//		FORMAT_I, FORMAT_I_MASK|0xfff00000,
//                ASM_SEQ2(ASM_REG_RD, ASM_COPY_RD_RS1)),

    // dec = addi <r>,<r>,-1
//   we can not match <r>, <r> in disasm yet so we wait
//    SYM_INSTR_X(dec, FORMAT_I_CODE(OPCODE_IMM, FUNCT_ADDI)|0xfff00000,
//		FORMAT_I, FORMAT_I_MASK|0xfff00000,
//                ASM_SEQ2(ASM_REG_RD, ASM_COPY_RD_RS1)),

};

int vasm_rv32i_asm_init(symbol_table_t* symtab)
{
    // link in static symbols above into symtab
    symbol_table_install_array(symtab, &sym_reg_abi[0], 
			       sizeof_array(sym_reg_abi));
    symbol_table_install_array(symtab, &sym_reg_xi[0],
			       sizeof_array(sym_reg_xi));
    symbol_table_install_array(symtab, &sym_instr_rv32i[0],
			       sizeof_array(sym_instr_rv32i));
    return 0;
}
