#include <ctype.h>
#include "vasm.h"

#include "vasm_rv32c.h"

symbol_t sym_instr_rv32c[] =
{
    SYM_INSTR_NAME_X(c_add, "c.add", OPCODE_C2, FUNCT_C_ADD, FORMAT_CR, 0,
		     ASM_SEQ2(ASM_REG_RD, ASM_REG_RS2)),
    SYM_INSTR_NAME_X(c_addi, "c.addi", OPCODE_C1, FUNCT_C_ADDI, FORMAT_CI, 0,
		     ASM_SEQ2(ASM_REG_RD,  ASM_IMM_6)),
    SYM_INSTR_NAME_X(c_addi16sp, "c.addi16sp", OPCODE_C1, FUNCT_C_ADDI16SP, FORMAT_CI, 0,
		     ASM_SEQ2(ASM_REG_RD,  ASM_IMM_6)),
    //
    SYM_INSTR_NAME_X(c_addi4spn, "c.addi4spn", OPCODE_C0, FUNCT_C_ADDI4SPN, FORMAT_CIW, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_addiw, "c.addiw", OPCODE_C1, FUNCT_C_ADDIW, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_addw, "c.addw", OPCODE_C1, FUNCT_C_ADDW, FORMAT_CR, 0,
		     ASM_SEQ2(ASM_REG_RD, ASM_REG_RS2)),
    SYM_INSTR_NAME_X(c_and, "c.and", OPCODE_C1, FUNCT_C_AND, FORMAT_CS, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_andi, "c.andi", OPCODE_C1, FUNCT_C_ANDI, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_beqz, "c.beqz", OPCODE_C1, FUNCT_C_BEQZ, FORMAT_CB, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_bnez, "c.bnez", OPCODE_C1, FUNCT_C_BNEZ, FORMAT_CB, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_ebreak, "c.ebreak", OPCODE_C2, FUNCT_C_EBREAK, FORMAT_CR, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_fld, "c.fld", OPCODE_C0, FUNCT_C_FLD, FORMAT_CL, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_fldsp, "c.fldsp", OPCODE_C2, FUNCT_C_FLDSP, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_flw, "c.flw", OPCODE_C0, FUNCT_C_FLW, FORMAT_CL, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_flwsp, "c.flwsp", OPCODE_C2, FUNCT_C_FLWSP, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_fsd, "c.fsd", OPCODE_C0, FUNCT_C_FSD, FORMAT_CL, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_fsdsp, "c.fsdsp", OPCODE_C2, FUNCT_C_FSDSP, FORMAT_CSS, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_fsw, "c.fsw", OPCODE_C0, FUNCT_C_FSW, FORMAT_CL, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_fswsp, "c.fswsp", OPCODE_C2, FUNCT_C_FSWSP, FORMAT_CSS, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_j, "c.j", OPCODE_C1, FUNCT_C_J, FORMAT_CJ, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_jalr, "c.jalr", OPCODE_C2, FUNCT_C_JALR, FORMAT_CR, 0,
		     ASM_SEQ2(ASM_RD_X1, ASM_REG_RS2)),
    SYM_INSTR_NAME_X(c_jr, "c.jr", OPCODE_C2, FUNCT_C_JR, FORMAT_CR, 0,
		     ASM_SEQ2(ASM_RD_X0, ASM_REG_RS2)),
    SYM_INSTR_NAME_X(c_ld, "c.ld", OPCODE_C0, FUNCT_C_LD, FORMAT_CL, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_ldsp, "c.ldsp", OPCODE_C2, FUNCT_C_LDSP, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_li, "c.li", OPCODE_C1, FUNCT_C_LI, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_lui, "c.lui", OPCODE_C1, FUNCT_C_LUI, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_lw, "c.lw", OPCODE_C0, FUNCT_C_LW, FORMAT_CL, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_lwsp, "c.lwsp", OPCODE_C2, FUNCT_C_LWSP, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_mv, "c.mv", OPCODE_C2, FUNCT_C_MV, FORMAT_CR, 0,
		     ASM_SEQ2(ASM_REG_RD, ASM_REG_RS2)),
    SYM_INSTR_NAME_X(c_nop, "c.nop", OPCODE_C1, FUNCT_C_NOP, FORMAT_CR, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_or, "c.or", OPCODE_C1, FUNCT_C_OR, FORMAT_CS, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_sd, "c.sd", OPCODE_C0, FUNCT_C_SD, FORMAT_CL, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_sdsp, "c.sdsp", OPCODE_C2, FUNCT_C_SDSP, FORMAT_CSS, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_slli, "c.slli", OPCODE_C2, FUNCT_C_SLLI, FORMAT_CI, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_srai, "c.srai", OPCODE_C1, FUNCT_C_SRAI, FORMAT_CB, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_srli, "c.srli", OPCODE_C1, FUNCT_C_SRLI, FORMAT_CB, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_sub, "c.sub", OPCODE_C1, FUNCT_C_SUB, FORMAT_CS, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_subw, "c.subw", OPCODE_C1, FUNCT_C_SUBW, FORMAT_CS, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_sw, "c.sw", OPCODE_C0, FUNCT_C_SW, FORMAT_CL, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_swsp, "c.swsp", OPCODE_C2, FUNCT_C_SWSP, FORMAT_CSS, 0,
		     ASM_SEQ0()),
    SYM_INSTR_NAME_X(c_xor, "c.xor", OPCODE_C1, FUNCT_C_XOR, FORMAT_CS, 0,
		     ASM_SEQ0()),
};

int vasm_rv32c_asm_init(symbol_table_t* symtab)
{
    // link in static symbols above into symtab
    symbol_table_install_array(symtab, &sym_instr_rv32c[0],
			       sizeof_array(sym_instr_rv32c));
    return 0;
}
